[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "exif>=1.6.1",
    "httpx>=0.28.1",
    "pydantic>=2.12.0",
    "tqdm>=4.67.1",
]
